resources:
- repo: self
phases:
- phase: Phase_1
  displayName: Build Windows

  condition: succeeded()
  queue:
    name: Hosted VS2017
  steps:
  - powershell: ./build.ps1
    displayName: Windows Script Build
    continueOnError: true

  - task: PublishTestResults@2
    displayName: 'Publish Window Test Results **/TestResults*.xml'
    inputs:
      testRunner: NUnit

      testResultsFiles: '**/TestResults*.xml'



- phase: Phase_2
  displayName: Build Linux

  condition: succeeded()
  queue:
    name: Hosted Ubuntu 1604
  steps:
  - powershell: ./build.ps1
    displayName: Linux Script Build
    continueOnError: true

  - task: PublishTestResults@2
    displayName: 'Publish Linux Test Results **/TestResults*.xml'
    inputs:
      testRunner: NUnit

      testResultsFiles: '**/TestResults*.xml'



- phase: Phase_3
  displayName: Build MacOS

  condition: succeeded()
  queue:
    name: Hosted macOS
  steps:
  - powershell: ./build.ps1
    displayName: MacOS Script Build
    continueOnError: true

  - task: PublishTestResults@2
    displayName: 'Publish macOS Test Results **/TestResults*.xml'
    inputs:
      testRunner: NUnit

      testResultsFiles: '**/TestResults*.xml'


